export const ADMIN_REGISTER_REQUEST = 'ADMIN_REGISTER_REQUEST';
export const ADMIN_REGISTER_SUCCESS = 'ADMIN_REGISTER_SUCCESS';
export const ADMIN_REGISTER_FAIL = 'ADMIN_REGISTER_FAIL';

export const ADMIN_SIGNIN_REQUEST = 'ADMIN_SIGNIN_REQUEST';
export const ADMIN_SIGNIN_SUCCESS = 'ADMIN_SIGNIN_SUCCESS';
export const ADMIN_SIGNIN_FAIL = 'ADMIN_SIGNIN_FAIL';

export const ADMIN_SIGNOUT = 'ADMIN_SIGNOUT';

export const ADD_SCHOOL_REQUEST = 'ADD_SCHOOL_REQUEST';
export const ADD_SCHOOL_SUCCESS = 'ADD_SCHOOL_SUCCESS';
export const ADD_SCHOOL_FAIL = 'ADD_SCHOOL_FAIL';
