export const SCHOOL_LIST_REQUEST = 'SCHOOL_LIST_REQUEST';
export const SCHOOL_LIST_SUCCESS = 'SCHOOL_LIST_SUCCESS';
export const SCHOOL_LIST_FAIL = 'SCHOOL_LIST_FAIL';

export const SCHOOL_INFO_REQUEST = 'SCHOOL_INFO_REQUEST';
export const SCHOOL_INFO_SUCCESS = 'SCHOOL_INFO_SUCCESS';
export const SCHOOL_INFO_FAIL = 'SCHOOL_INFO_FAIL';