export const SCHOOL_LIST_REQUEST = 'SCHOOL_LIST_REQUEST';
export const SCHOOL_LIST_SUCCESS = 'SCHOOL_LIST_SUCCESS';
export const SCHOOL_LIST_FAIL = 'SCHOOL_LIST_FAIL';

export const SCHOOL_INFO_REQUEST = 'SCHOOL_INFO_REQUEST';
export const SCHOOL_INFO_SUCCESS = 'SCHOOL_INFO_SUCCESS';
export const SCHOOL_INFO_FAIL = 'SCHOOL_INFO_FAIL';

export const SCHOOL_ID_REQUEST = 'SCHOOL_ID_REQUEST';
export const SCHOOL_ID_SUCCESS = 'SCHOOL_ID_SUCCESS';
export const SCHOOL_ID_FAIL = 'SCHOOL_ID_FAIL';

export const ADD_YOURSELF_REQUEST = 'ADD_YOURSELF_REQUEST';
export const ADD_YOURSELF_SUCCESS = 'ADD_YOURSELF_SUCCESS';
export const ADD_YOURSELF_FAIL = 'ADD_YOURSELF_FAIL';